[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Informfully"
authors = [{name = "Lucien Heitz", email = "heitz@ifi.uzh.ch"}]
dynamic = ["version", "description"]
